Repository ISIS3510-202410-Team-13/Flutter, pull requests merged in 2024-04, with the labels that each got.

#51 Initial Version of the Groups Page Implemented
  unischedule/assets/images/profile_pics/user_1.png
  unischedule/assets/images/profile_pics/user_10.png
  unischedule/assets/images/profile_pics/user_11.png
  unischedule/assets/images/profile_pics/user_2.png
  unischedule/assets/images/profile_pics/user_3.png
  unischedule/assets/images/profile_pics/user_4.png
  unischedule/assets/images/profile_pics/user_5.png
  unischedule/assets/images/profile_pics/user_6.png
  unischedule/assets/images/profile_pics/user_7.png
  unischedule/assets/images/profile_pics/user_8.png
  unischedule/assets/images/profile_pics/user_9.png
  unischedule/lib/presentation/bottom_navbar/bottom_navbar.dart
  unischedule/lib/presentation/calendar_page/calendar_page.dart
  unischedule/lib/presentation/groups_page/groups_page.dart
  unischedule/lib/routes/go_router_provider.dart
  unischedule/pubspec.yaml
Labels: GUI

#55 Implemented Friends View
  unischedule/lib/presentation/bottom_navbar/bottom_navbar.dart
  unischedule/lib/presentation/friends_page/friends_page.dart
  unischedule/lib/routes/go_router_provider.dart
Labels: GUI

#56 Need Develop Changes in Local Branch
  unischedule/assets/images/profile_pics/user_1.png
  unischedule/assets/images/profile_pics/user_10.png
  unischedule/assets/images/profile_pics/user_11.png
  unischedule/assets/images/profile_pics/user_2.png
  unischedule/assets/images/profile_pics/user_3.png
  unischedule/assets/images/profile_pics/user_4.png
  unischedule/assets/images/profile_pics/user_5.png
  unischedule/assets/images/profile_pics/user_6.png
  unischedule/assets/images/profile_pics/user_7.png
  unischedule/assets/images/profile_pics/user_8.png
  unischedule/assets/images/profile_pics/user_9.png
  unischedule/lib/presentation/bottom_navbar/bottom_navbar.dart
  unischedule/lib/presentation/calendar_page/calendar_page.dart
  unischedule/lib/presentation/friends_page/friends_page.dart
  unischedule/lib/presentation/groups_page/groups_page.dart
  unischedule/lib/routes/go_router_provider.dart
  unischedule/pubspec.yaml
Labels: bug

#58 Bring Develop Changes to local Branch
  unischedule/assets/images/profile_pics/user_1.png
  unischedule/assets/images/profile_pics/user_10.png
  unischedule/assets/images/profile_pics/user_11.png
  unischedule/assets/images/profile_pics/user_2.png
  unischedule/assets/images/profile_pics/user_3.png
  unischedule/assets/images/profile_pics/user_4.png
  unischedule/assets/images/profile_pics/user_5.png
  unischedule/assets/images/profile_pics/user_6.png
  unischedule/assets/images/profile_pics/user_7.png
  unischedule/assets/images/profile_pics/user_8.png
  unischedule/assets/images/profile_pics/user_9.png
  unischedule/lib/presentation/bottom_navbar/bottom_navbar.dart
  unischedule/lib/presentation/calendar_page/calendar_page.dart
  unischedule/lib/presentation/friends_page/friends_page.dart
  unischedule/lib/presentation/groups_page/groups_page.dart
  unischedule/lib/presentation/rating-bar_page/rating-bar_page.dart
  unischedule/lib/routes/go_router_provider.dart
  unischedule/pubspec.yaml
Labels: bug

#61 Enhanced Search Bar Functionality and Style
  unischedule/lib/presentation/friends_page/friends_page.dart
  unischedule/lib/presentation/groups_page/groups_page.dart
Labels: bug, GUI

#78 64 changing existing views to render dynamic data
  unischedule/lib/constants/http/http_constants.dart
  unischedule/lib/models/friends_page/friend_model.dart
  unischedule/lib/models/groups_page/group_model.dart
  unischedule/lib/presentation/friends_page/friends_page.dart
  unischedule/lib/presentation/groups_page/groups_page.dart
  unischedule/lib/presentation/home_page/home_page.dart
  unischedule/lib/providers/friends_page/friends_provider.dart
  unischedule/lib/providers/groups_page/groups_provider.dart
  unischedule/lib/repositories/friends_page/friends_page_repository.dart
  unischedule/lib/repositories/groups_page/groups_page_repository.dart
  unischedule/lib/services/network/friends_api_service.dart
  unischedule/lib/services/network/groups_api_service.dart
Labels: feature

#80 Multi-threading feature for API call of Friends and Groups Implemented
  unischedule/lib/presentation/authentication_page/authentication_page.dart
  unischedule/lib/presentation/friends_page/friends_page.dart
  unischedule/lib/presentation/groups_page/groups_page.dart
Labels: feature

#82 Implement local filtering for Friends and Groups using StateNotifier
  unischedule/lib/presentation/authentication_page/authentication_page.dart
  unischedule/lib/presentation/friends_page/friends_page.dart
  unischedule/lib/presentation/groups_page/groups_page.dart
  unischedule/lib/providers/friends_page/friends_provider.dart
  unischedule/lib/providers/friends_page/friends_state_notifier.dart
  unischedule/lib/providers/groups_page/groups_state_notifier.dart
  unischedule/lib/repositories/friends_page/friends_page_repository.dart
Labels: feature

#84 Create and Style Slide-Out Menu
  unischedule/lib/presentation/calendar_page/calendar_page.dart
  unischedule/lib/presentation/friends_page/friends_page.dart
  unischedule/lib/presentation/groups_page/groups_page.dart
  unischedule/lib/presentation/home_page/home_page.dart
  unischedule/lib/presentation/shell/app_shell.dart
  unischedule/lib/presentation/slide-out_page/slide-out_page.dart
Labels: GUI

#86 Add event handling functionality
  unischedule/lib/constants/http/http_constants.dart
  unischedule/lib/models/events_page/event_model.dart
  unischedule/lib/presentation/authentication_page/authentication_page.dart
  unischedule/lib/providers/events_page/events_provider.dart
  unischedule/lib/repositories/events_page/events_repository.dart
  unischedule/lib/services/network/events_api_service.dart
Labels: feature

#90 Cache strategy for network Images: Profile Icons
  unischedule/lib/presentation/friends_page/friends_page.dart
  unischedule/lib/presentation/groups_page/groups_page.dart
  unischedule/pubspec.yaml
Labels: feature

#88 Initial Implementation of local storage strategy for events, friends and groups (Just Saving for now)
  unischedule/lib/main.dart
  unischedule/lib/models/boxes.dart
  unischedule/lib/models/events_page/event_model.dart
  unischedule/lib/models/friends_page/friend_model.dart
  unischedule/lib/models/groups_page/group_model.dart
  unischedule/lib/presentation/authentication_page/authentication_page.dart
  unischedule/lib/presentation/friends_page/friends_page.dart
  unischedule/lib/presentation/groups_page/groups_page.dart
  unischedule/lib/presentation/slide-out_page/slide-out_page.dart
  unischedule/lib/presentation/temp-cache_page/temp-cache_page.dart
  unischedule/lib/providers/friends_page/friends_state_notifier.dart
  unischedule/lib/providers/groups_page/groups_state_notifier.dart
  unischedule/lib/routes/go_router_provider.dart
  unischedule/pubspec.yaml
Labels: feature

#95 Refactor Calendar View into Multiple Widgets
  unischedule/lib/presentation/calendar_page/calendar_page.dart
  unischedule/lib/presentation/calendar_page/widgets/calendar_app_bar.dart
  unischedule/lib/presentation/calendar_page/widgets/calendar_background.dart
  unischedule/lib/presentation/calendar_page/widgets/calendar_fab.dart
  unischedule/lib/presentation/calendar_page/widgets/calendar_time_lines.dart
  unischedule/lib/presentation/calendar_page/widgets/calendar_week_days.dart
Labels: tech-debt

#94 Add App icon and basic splash
  unischedule/android/app/src/main/AndroidManifest.xml
  unischedule/android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  unischedule/android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  unischedule/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  unischedule/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  unischedule/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  unischedule/assets/app-icon/logo.png
  unischedule/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png
  unischedule/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
  unischedule/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
  unischedule/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
  unischedule/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
  unischedule/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
  unischedule/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
  unischedule/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
  unischedule/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
  unischedule/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
  unischedule/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-50x50@1x.png
  unischedule/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-50x50@2x.png
  unischedule/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-57x57@1x.png
  unischedule/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-57x57@2x.png
  unischedule/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
  unischedule/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
  unischedule/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-72x72@1x.png
  unischedule/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-72x72@2x.png
  unischedule/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
  unischedule/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
  unischedule/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
  unischedule/pubspec.yaml
Labels: GUI

#93 Update Service and Repository to use the new deployed AvailableSpaces backend service
  unischedule/lib/constants/http/http_constants.dart
  unischedule/lib/repositories/create-class_page/create-class_repository.dart
  unischedule/lib/services/network/available-spaces_api_service.dart
Labels: bug

#96 Fix Persistent Filtering Bug on Friends and Groups Navigation
  unischedule/lib/presentation/friends_page/friends_page.dart
  unischedule/lib/presentation/groups_page/groups_page.dart
  unischedule/lib/providers/friends_page/friends_state_notifier.dart
  unischedule/lib/providers/groups_page/groups_state_notifier.dart
Labels: bug

#97 Create personal events
  unischedule/lib/presentation/authentication_page/authentication_page.dart
  unischedule/lib/presentation/calendar_page/calendar_page.dart
  unischedule/lib/presentation/calendar_page/widgets/calendar_event.dart
  unischedule/lib/presentation/calendar_page/widgets/calendar_time_lines.dart
  unischedule/lib/presentation/calendar_page/widgets/calendar_week_days.dart
  unischedule/lib/presentation/create-class_page/create-class_page.dart
  unischedule/lib/providers/events_page/events_state_notifier.dart
Labels: feature, GUI

#104 Local Storage for friends and groups, and text messages for status of the lists
  unischedule/lib/providers/friends/friends_provider.dart
  unischedule/lib/repositories/friends/friends_repository.dart
  unischedule/lib/repositories/groups/groups_repository.dart
  unischedule/lib/services/local_storage/hive_box_service.dart
  unischedule/lib/views/friends/friends_view.dart
  unischedule/lib/views/groups/groups_view.dart
Labels: feature

#105 Events Local Storage and Sync Functionality
  unischedule/lib/constants/strings/local_storage_constants.dart
  unischedule/lib/repositories/events/events_repository.dart
  unischedule/lib/repositories/friends/friends_repository.dart
  unischedule/lib/repositories/groups/groups_repository.dart
  unischedule/lib/services/local_storage/hive_box_service.dart
  unischedule/lib/views/new_event/widgets/new_event_form.dart
  unischedule/lib/widgets/app_shell/app_shell_widget.dart
Labels: feature

#106 Implement Feature for Creating Personal Events with Calendar Rendering
  unischedule/lib/views/new_event/widgets/color_picker_button.dart
  unischedule/pubspec.yaml
Labels: feature

#107 Calendar One Page Implemented
  unischedule/lib/views/calendar/calendar_view.dart
  unischedule/lib/views/calendar/widgets/calendar_event.dart
  unischedule/lib/views/calendar/widgets/calendar_time_lines.dart
Labels: feature, GUI

#103 Authentication with firebase
  unischedule/ios/Runner.xcodeproj/project.pbxproj
  unischedule/lib/constants/colors/color_constants.dart
  unischedule/lib/constants/strings/string_constants.dart
  unischedule/lib/constants/theme/text_theme.dart
  unischedule/lib/providers/authentication/authentication_provider.dart
  unischedule/lib/providers/providers.dart
  unischedule/lib/repositories/events/events_repository.dart
  unischedule/lib/repositories/friends/friends_repository.dart
  unischedule/lib/repositories/groups/groups_repository.dart
  unischedule/lib/services/local_storage/hive_box_service.dart
  unischedule/lib/views/authentication/authentication_view.dart
  unischedule/lib/views/authentication/widgets/login_dialog.dart
  unischedule/lib/views/authentication/widgets/new_user_options.dart
  unischedule/lib/views/authentication/widgets/old_user_options.dart
  unischedule/lib/views/authentication/widgets/signup_dialog.dart
  unischedule/lib/views/groups/groups_view.dart
  unischedule/lib/views/home/home_view.dart
  unischedule/lib/widgets/app_shell/drawer_widget.dart
  unischedule/pubspec.yaml
Labels: feature, GUI

#109 Fix error when rendering profile icons in groups card when there are less than 3 members
  unischedule/lib/views/groups/widgets/group_card.dart
  unischedule/lib/views/groups/widgets/profile_icons_row.dart
Labels: bug

#108 Fix error when calculating earliestStart and latestEnd values for empty events list in Calendar view
  unischedule/lib/views/calendar/calendar_view.dart
Labels: bug

#111 Add empty state handling for groups and events in HomeView
  unischedule/lib/views/home/home_view.dart
Labels: GUI

#114 Meeting Place Recommendation Disabled when not Internet Connection
  unischedule/lib/providers/connectivity/connectivity_provider.dart
  unischedule/lib/views/new_event/widgets/new_event_form.dart
  unischedule/pubspec.yaml
Labels: feature

#112 Fix rendering error that does not shown the text when there are more …
  unischedule/lib/views/groups/widgets/group_card.dart
  unischedule/lib/views/groups/widgets/profile_icons_row.dart
Labels: bug

#120 Fixing the functionality of the Floating Action Button (FAB) to navig…
  unischedule/lib/routes/shell_routes.dart
  unischedule/lib/widgets/app_shell/app_fab_widget.dart
  unischedule/lib/widgets/app_shell/app_shell_widget.dart
Labels: bug

#122 Now the events that has a different day at start and end are rendered
  unischedule/lib/views/calendar/calendar_view.dart
  unischedule/lib/views/calendar/widgets/calendar_event.dart
  unischedule/lib/views/calendar/widgets/calendar_time_lines.dart
Labels: bug

#121 Add Connectivity Status Icon to UniScheduleAppBar
  unischedule/lib/constants/strings/asset_constants.dart
  unischedule/lib/widgets/app_shell/app_bar_widget.dart
Labels: feature, GUI

#123 Fixed error when building the request for available spaces. Also, added error and loading views
  unischedule/android/app/src/main/AndroidManifest.xml
  unischedule/lib/providers/available_spaces/available_spaces_provider.dart
  unischedule/lib/views/groups/widgets/profile_icons_row.dart
  unischedule/lib/views/new_event/widgets/place_recommendation_dialog.dart
Labels: bug

#125 Fix scheduled notifications not working
  unischedule/android/app/build.gradle
  unischedule/android/app/src/main/AndroidManifest.xml
  unischedule/android/app/src/main/res/drawable-hdpi/unischedule_icon.png
  unischedule/android/app/src/main/res/drawable-mdpi/unischedule_icon.png
  unischedule/android/app/src/main/res/drawable-xhdpi/unischedule_icon.png
  unischedule/android/app/src/main/res/drawable-xxhdpi/unischedule_icon.png
  unischedule/android/app/src/main/res/drawable-xxxhdpi/unischedule_icon.png
  unischedule/android/app/src/main/res/drawable/flutter_logo.png
  unischedule/lib/main.dart
  unischedule/lib/services/notifications/notifications_service.dart
Labels: bug

#126 Enhance error handling in authentication process
  unischedule/lib/constants/strings/string_constants.dart
  unischedule/lib/providers/authentication/authentication_provider.dart
  unischedule/lib/views/authentication/widgets/login_dialog.dart
  unischedule/lib/views/authentication/widgets/signup_dialog.dart
Labels: feature, GUI

#127 Create providers for sending analytics information regarding buttons …
  unischedule/lib/constants/analytics/analytics_constants.dart
  unischedule/lib/constants/constants.dart
  unischedule/lib/constants/http/http_constants.dart
  unischedule/lib/main.dart
  unischedule/lib/providers/connectivity/connectivity_provider.dart
  unischedule/lib/providers/feature_analytics/feature_analytics_provider.dart
  unischedule/lib/providers/providers.dart
  unischedule/lib/repositories/feature_analytics/feature_analytics_repository.dart
  unischedule/lib/repositories/repositories.dart
  unischedule/lib/routes/root_routes.dart
  unischedule/lib/views/authentication/widgets/new_user_options.dart
  unischedule/lib/views/new_event/widgets/color_picker_button.dart
  unischedule/lib/views/new_event/widgets/new_event_form.dart
  unischedule/lib/widgets/app_shell/drawer_widget.dart
Labels: feature
