Repository ISIS3510-202410-Team-13/Flutter, pull requests merged in 2024-03, with the labels that each got.

#7 Finished Calendar Page GUI
  unischedule/lib/presentation/calendar_page/calendar_page.dart
Labels: GUI

#8 Home Page GUI created
  unischedule/lib/presentation/home_page/home_page.dart
Labels: GUI

#10 Bottom Navigation Implementated
  unischedule/lib/presentation/bottom_navbar/bottom_navbar.dart
Labels: GUI

#14 Add navigation bar controller
  unischedule/lib/providers/navigation/navigation_bar_controller.dart
Labels: feature

#13 Create and implement app shell
  unischedule/lib/presentation/shell/app_shell.dart
Labels: GUI

#16 Add GoRouter Provider for Enhanced Navigation Management
  unischedule/lib/routes/go_router_provider.dart
Labels: feature

#22 First version of Biometric Authentication Feature
  unischedule/android/app/src/main/AndroidManifest.xml
  unischedule/android/app/src/main/kotlin/com/example/unischedule/MainActivity.kt
  unischedule/lib/presentation/authentication_page/authentication_page.dart
  unischedule/lib/presentation/home_page/home_page.dart
  unischedule/lib/routes/go_router_provider.dart
  unischedule/pubspec.yaml
Labels: feature

#24 Implement Initial Auth Flow and Adjust Navigation
  unischedule/lib/presentation/authentication_page/authentication_page.dart
  unischedule/lib/presentation/bottom_navbar/bottom_navbar.dart
  unischedule/lib/routes/go_router_provider.dart
Labels: feature

#26 Add new class GUI
  unischedule/.gitignore
  unischedule/ios/Flutter/Debug.xcconfig
  unischedule/ios/Flutter/Release.xcconfig
  unischedule/ios/Runner.xcodeproj/project.pbxproj
  unischedule/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  unischedule/ios/Runner.xcworkspace/contents.xcworkspacedata
  unischedule/lib/presentation/calendar_page/calendar_page.dart
  unischedule/lib/presentation/create-class_page/create-class_page.dart
  unischedule/lib/routes/go_router_provider.dart
  unischedule/pubspec.yaml
Labels: GUI

#29 First version of Push Notifications
  unischedule/android/app/build.gradle
  unischedule/android/app/src/main/AndroidManifest.xml
  unischedule/android/app/src/main/res/drawable/flutter_logo.png
  unischedule/lib/main.dart
  unischedule/lib/presentation/notifications_page/notifications_page.dart
  unischedule/lib/routes/go_router_provider.dart
  unischedule/lib/services/notifications_service.dart
  unischedule/pubspec.yaml
Labels: feature

#32 Enhance Event Creation Flow with Date/Time Selection
  unischedule/lib/presentation/create-class_page/create-class_page.dart
  unischedule/lib/routes/go_router_provider.dart
  unischedule/pubspec.yaml
Labels: feature

#34 Implement new feature to suggest available spaces - Flutter
  unischedule/.gitignore
  unischedule/README.md
  unischedule/assets/images/buildings/AU.jpg
  unischedule/assets/images/buildings/B.jpg
  unischedule/assets/images/buildings/C.jpg
  unischedule/assets/images/buildings/LL.jpg
  unischedule/assets/images/buildings/ML.jpg
  unischedule/assets/images/buildings/O.jpg
  unischedule/assets/images/buildings/R.jpg
  unischedule/assets/images/buildings/RGD.jpg
  unischedule/assets/images/buildings/SD.jpg
  unischedule/assets/images/buildings/W.jpg
  unischedule/lib/constants/http/http_constants.dart
  unischedule/lib/models/create-class_page/create-class_model.dart
  unischedule/lib/presentation/create-class_page/create-class_page.dart
  unischedule/lib/providers/create-class_page/create-class_provider.dart
  unischedule/lib/repositories/create-class_page/create-class_repository.dart
  unischedule/lib/services/network/available-spaces_api_service.dart
  unischedule/pubspec.yaml
Labels: feature

#36 35 create a new pop up for rating recommendations
  unischedule/lib/presentation/create-class_page/create-class_page.dart
  unischedule/lib/presentation/rating-bar_page/rating-bar_page.dart
  unischedule/lib/routes/go_router_provider.dart
  unischedule/pubspec.yaml
Labels: feature

#38 Lock screen orientation to portrait mode
  unischedule/android/app/src/main/AndroidManifest.xml
  unischedule/lib/main.dart
Labels: feature, GUI

#40 Translate text to english
  unischedule/lib/presentation/authentication_page/authentication_page.dart
  unischedule/lib/presentation/create-class_page/create-class_page.dart
  unischedule/lib/presentation/home_page/home_page.dart
Labels: bug, GUI

#43 Fix bug related to overflowed widget with keyboard
  unischedule/lib/presentation/bottom_navbar/bottom_navbar.dart
  unischedule/lib/presentation/create-class_page/create-class_page.dart
Labels: bug

#44 Add troubleshooting and architecture information to README
  README.md
Labels: documentation
