Repository ISIS3510-202410-Team-13/Flutter, pull requests merged in 2024-05, with the labels that each got.

#130 Place Recommendation Analytics
  unischedule/lib/constants/analytics/analytics_constants.dart
  unischedule/lib/constants/strings/asset_constants.dart
  unischedule/lib/constants/strings/string_constants.dart
  unischedule/lib/constants/theme/text_theme.dart
  unischedule/lib/providers/authentication/authentication_provider.dart
  unischedule/lib/providers/available_spaces/available_spaces_provider.dart
  unischedule/lib/providers/feature_analytics/feature_analytics_provider.dart
  unischedule/lib/repositories/available_spaces/available_spaces_repository.dart
  unischedule/lib/repositories/feature_analytics/feature_analytics_repository.dart
  unischedule/lib/views/new_event/widgets/color_picker_button.dart
  unischedule/lib/views/new_event/widgets/place_recommendation_dialog.dart
  unischedule/lib/views/new_event/widgets/rating_bottom_sheet.dart
Labels: bug, feature, GUI

#133 Implement Notification View with Custom Widgets for Different Notific…
  unischedule/lib/models/models.dart
  unischedule/lib/models/notifications/notification.dart
  unischedule/lib/views/notifications/notifications_view.dart
  unischedule/lib/views/notifications/widgets/notification_widget.dart
  unischedule/lib/views/notifications/widgets/notifications_app_bar.dart
Labels: GUI

#134 Create new group view added
  unischedule/lib/constants/strings/route_constants.dart
  unischedule/lib/routes/root_routes.dart
  unischedule/lib/routes/shell_routes.dart
  unischedule/lib/views/friends/friends_view.dart
  unischedule/lib/views/friends/widgets/friend_card.dart
  unischedule/lib/views/new_event/widgets/new_event_form.dart
  unischedule/lib/views/new_group/new_group_app_bar.dart
  unischedule/lib/views/new_group/new_group_form.dart
  unischedule/lib/views/new_group/new_group_view.dart
Labels: GUI

#142 Working External Notifications in Main and Background Task
  unischedule/android/build.gradle
  unischedule/lib/main.dart
  unischedule/pubspec.yaml
Labels: feature

#144 139 local storage for notifications
  unischedule/lib/constants/http/http_constants.dart
  unischedule/lib/constants/strings/local_storage_constants.dart
  unischedule/lib/main.dart
  unischedule/lib/models/models.dart
  unischedule/lib/models/notifications/notification.dart
  unischedule/lib/models/notifications/notification_model.dart
  unischedule/lib/providers/notifications/notifications_provider.dart
  unischedule/lib/providers/providers.dart
  unischedule/lib/repositories/notifications/notifications_repository.dart
  unischedule/lib/repositories/repositories.dart
  unischedule/lib/services/local_storage/hive_box_service.dart
  unischedule/lib/views/notifications/notifications_view.dart
  unischedule/lib/views/notifications/widgets/notifications_app_bar.dart
  unischedule/lib/widgets/app_shell/app_bar_widget.dart
Labels: feature, GUI

#146 Handle Eventual Connectivity in Notifications View
  unischedule/lib/models/notifications/notification.dart
  unischedule/lib/views/notifications/notifications_view.dart
  unischedule/lib/views/notifications/widgets/notification_widget.dart
Labels: feature

#148 Implement the Group Creation Feature
  unischedule/lib/providers/groups/groups_provider.dart
  unischedule/lib/repositories/groups/groups_repository.dart
  unischedule/lib/views/groups/groups_view.dart
  unischedule/lib/views/new_group/new_group_form.dart
Labels: feature

#149 Implement Image Caching for Notifications
  unischedule/lib/views/notifications/widgets/notification_widget.dart
Labels: feature, GUI

#151 Group Creation ECs Implemented
  unischedule/lib/views/new_group/new_group_form.dart
Labels: feature

#152 Chat view
  unischedule/lib/constants/colors/color_constants.dart
  unischedule/lib/providers/friends/friends_provider.dart
  unischedule/lib/routes/root_routes.dart
  unischedule/lib/views/chat/chat_view.dart
  unischedule/lib/views/chat/widgets/chat_bottom_bar.dart
  unischedule/lib/views/chat/widgets/chat_bubble.dart
  unischedule/lib/views/chat/widgets/chat_top_bar.dart
  unischedule/lib/views/friends/friends_view.dart
  unischedule/pubspec.yaml
Labels: GUI

#153 Chat Features (send and receive messages)
  unischedule/lib/models/chat/message_model.dart
  unischedule/lib/providers/authentication/authentication_provider.dart
  unischedule/lib/services/chat/chat_service.dart
  unischedule/lib/views/chat/chat_view.dart
  unischedule/lib/views/chat/widgets/chat_bottom_bar.dart
  unischedule/lib/views/chat/widgets/message_list.dart
  unischedule/lib/views/friends/friends_view.dart
  unischedule/lib/views/friends/widgets/friend_card.dart
  unischedule/lib/views/groups/widgets/profile_icons_row.dart
  unischedule/lib/widgets/app_shell/drawer_widget.dart
Labels: feature

#154 Chat Eventual Connectivity, Local Storage and Caching Strategies
  unischedule/lib/constants/strings/local_storage_constants.dart
  unischedule/lib/main.dart
  unischedule/lib/models/chat/chat_model.dart
  unischedule/lib/models/chat/message_model.dart
  unischedule/lib/models/models.dart
  unischedule/lib/services/chat/chat_service.dart
  unischedule/lib/services/local_storage/hive_box_service.dart
  unischedule/lib/views/chat/chat_view.dart
  unischedule/lib/views/chat/widgets/chat_bottom_bar.dart
  unischedule/lib/views/chat/widgets/message_list.dart
Labels: feature
